---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: jai-and-rafa
spec:
  clusterRef:
    name: minecraft-cluster
  replicas: 1
  template:
    spec:
      clusterRef:
        name: minecraft-cluster
      podOverrides:
        containers:
          volumeMounts:
            - name: world
              mountPath: /data
        volumes:
          -  name: world
             persistentVolumeClaim:
               claimName: jai-and-rafa-world
               readOnly: false
      tags:
        - jai
        - rafa
      version:
        channel: Paper
        customJar:
          url: https://api.purpurmc.org/v2/purpur/1.21.4/latest/download
        name: "1.21.4"
      config: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
