---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServer
metadata:
  name: jai-and-rafa
spec:
  clusterRef:
    name: minecraft-cluster
  config:
    disableEnd: false
    disableNether: false
  podOverrides:
    volumeMounts:
      - name: world
        mountPath: /data/world
      - name: nether
        mountPath: /data/world_nether
      - name: end
        mountPath: /data/world_the_end
    volumes:
      -  name: world
         persistentVolumeClaim:
           claimName: jai-and-rafa-world
           readOnly: false
      -  name: nether
         persistentVolumeClaim:
           claimName: jai-and-rafa-nether
           readOnly: false
      -  name: end
         persistentVolumeClaim:
           claimName: jai-and-rafa-end
           readOnly: false
  tags:
    - jai
    - rafa
  version:
    channel: Paper
    name: "1.21.4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-end
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-nether
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
