---
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: jai-and-rafa
spec:
  clusterRef:
    name: minecraft-cluster
  replicas: 1
  template:
    spec:
      clusterRef:
        name: minecraft-cluster
      config:
        disableEnd: false
        disableNether: false
      podOverrides:
        volumeMounts:
          - name: world
            mountPath: /data/world
          - name: nether
            mountPath: /data/world_nether
          - name: end
            mountPath: /data/world_the_end
        volumes:
          -  name: world
             persistentVolumeClaim:
               claimName: jai-and-rafa-world
               readOnly: false
          -  name: nether
             persistentVolumeClaim:
               claimName: jai-and-rafa-nether
               readOnly: false
          -  name: end
             persistentVolumeClaim:
               claimName: jai-and-rafa-end
               readOnly: false
      tags:
        - jai
        - rafa
      version:
        channel: Paper
        customJar:
          url: https://api.purpurmc.org/v2/purpur/1.21.4/latest/download
        name: "1.21.4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-end
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-nether
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jai-and-rafa-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-xfs
